service: serverless-js

frameworkVersion: '3'

# Stages & Region 
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev 
  region: ap-northeast-1

# Lambda Functions 
functions:
  hello:
    handler: src/handler.generateRandomNumber
    timeout: 60 # seconds 
    memorySize: 128 #mb
