name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest # which os option 
    strategy:
      matrix:
        node-version: [14.x, 16.x] # node version 
    steps:
    - uses: actions/checkout@v2 # checkout project structures 
    - name: Use Node.js ${{ matrix.node-version }} 
      uses: actions/setup-node@v1 
      with:
        node-version: ${{ matrix.node-version }}
    # - run: npm ci # for nodejs dependencies 
    - name: serverless deploy
      uses: serverless/github-action@v3
      with:
        args: deploy
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        # or if using AWS credentials directly 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}